from ufc_data_scraper.data_models.event.accolade import Accolade
from ufc_data_scraper.data_models.event.card_segment import CardSegment
from ufc_data_scraper.data_models.event.event import Event
from ufc_data_scraper.data_models.event.fight_score import FightScore
from ufc_data_scraper.data_models.event.fight import Fight
from ufc_data_scraper.data_models.event.fighter_stats import FighterStats
from ufc_data_scraper.data_models.event.location import Location
from ufc_data_scraper.data_models.event.result import Result
from ufc_data_scraper.data_models.event.rule_set import RuleSet
from ufc_data_scraper.data_models.event.weight_class import WeightClass
